#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Bmas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CVT_DESAINT")]
	public partial class DBML_DesaintDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCVT_Usuarios(CVT_Usuarios instance);
    partial void UpdateCVT_Usuarios(CVT_Usuarios instance);
    partial void DeleteCVT_Usuarios(CVT_Usuarios instance);
    partial void InsertCVT_SubMenu(CVT_SubMenu instance);
    partial void UpdateCVT_SubMenu(CVT_SubMenu instance);
    partial void DeleteCVT_SubMenu(CVT_SubMenu instance);
    partial void InsertCVT_Menu(CVT_Menu instance);
    partial void UpdateCVT_Menu(CVT_Menu instance);
    partial void DeleteCVT_Menu(CVT_Menu instance);
    partial void InsertCVT_PrivilegioPerfil(CVT_PrivilegioPerfil instance);
    partial void UpdateCVT_PrivilegioPerfil(CVT_PrivilegioPerfil instance);
    partial void DeleteCVT_PrivilegioPerfil(CVT_PrivilegioPerfil instance);
    #endregion
		
		public DBML_DesaintDataContext() : 
				base(global::DB_Bmas.Properties.Settings.Default.CVT_DESAINTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_DesaintDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_DesaintDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_DesaintDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_DesaintDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CVT_Usuarios> CVT_Usuarios
		{
			get
			{
				return this.GetTable<CVT_Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<CVT_SubMenu> CVT_SubMenu
		{
			get
			{
				return this.GetTable<CVT_SubMenu>();
			}
		}
		
		public System.Data.Linq.Table<CVT_Menu> CVT_Menu
		{
			get
			{
				return this.GetTable<CVT_Menu>();
			}
		}
		
		public System.Data.Linq.Table<CVT_PrivilegioPerfil> CVT_PrivilegioPerfil
		{
			get
			{
				return this.GetTable<CVT_PrivilegioPerfil>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CVT_Usuarios")]
	public partial class CVT_Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _UsuarioSistema;
		
		private string _Clave;
		
		private string _NombreUsuario;
		
		private int _Id_Area;
		
		private string _Depto;
		
		private System.DateTime _FechaRegistro;
		
		private System.DateTime _FechaUpdate;
		
		private int _IdPerfil;
		
		private string _MailUsuario;
		
		private string _ClaveEncriptada;
		
		private System.Nullable<bool> _Verificador;
		
		private string _RutaFirma;
		
		private string _RutaFoto;
		
		private string _RestriccionBodega;
		
		private System.Nullable<int> _IdPerfilMovile;
		
		private System.Nullable<int> _TelefonoContacto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnUsuarioSistemaChanging(string value);
    partial void OnUsuarioSistemaChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnId_AreaChanging(int value);
    partial void OnId_AreaChanged();
    partial void OnDeptoChanging(string value);
    partial void OnDeptoChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnFechaUpdateChanging(System.DateTime value);
    partial void OnFechaUpdateChanged();
    partial void OnIdPerfilChanging(int value);
    partial void OnIdPerfilChanged();
    partial void OnMailUsuarioChanging(string value);
    partial void OnMailUsuarioChanged();
    partial void OnClaveEncriptadaChanging(string value);
    partial void OnClaveEncriptadaChanged();
    partial void OnVerificadorChanging(System.Nullable<bool> value);
    partial void OnVerificadorChanged();
    partial void OnRutaFirmaChanging(string value);
    partial void OnRutaFirmaChanged();
    partial void OnRutaFotoChanging(string value);
    partial void OnRutaFotoChanged();
    partial void OnRestriccionBodegaChanging(string value);
    partial void OnRestriccionBodegaChanged();
    partial void OnIdPerfilMovileChanging(System.Nullable<int> value);
    partial void OnIdPerfilMovileChanged();
    partial void OnTelefonoContactoChanging(System.Nullable<int> value);
    partial void OnTelefonoContactoChanged();
    #endregion
		
		public CVT_Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioSistema", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioSistema
		{
			get
			{
				return this._UsuarioSistema;
			}
			set
			{
				if ((this._UsuarioSistema != value))
				{
					this.OnUsuarioSistemaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioSistema = value;
					this.SendPropertyChanged("UsuarioSistema");
					this.OnUsuarioSistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Area", DbType="Int NOT NULL")]
		public int Id_Area
		{
			get
			{
				return this._Id_Area;
			}
			set
			{
				if ((this._Id_Area != value))
				{
					this.OnId_AreaChanging(value);
					this.SendPropertyChanging();
					this._Id_Area = value;
					this.SendPropertyChanged("Id_Area");
					this.OnId_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Depto", DbType="NVarChar(100)")]
		public string Depto
		{
			get
			{
				return this._Depto;
			}
			set
			{
				if ((this._Depto != value))
				{
					this.OnDeptoChanging(value);
					this.SendPropertyChanging();
					this._Depto = value;
					this.SendPropertyChanged("Depto");
					this.OnDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUpdate", DbType="DateTime NOT NULL")]
		public System.DateTime FechaUpdate
		{
			get
			{
				return this._FechaUpdate;
			}
			set
			{
				if ((this._FechaUpdate != value))
				{
					this.OnFechaUpdateChanging(value);
					this.SendPropertyChanging();
					this._FechaUpdate = value;
					this.SendPropertyChanged("FechaUpdate");
					this.OnFechaUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPerfil", DbType="Int NOT NULL")]
		public int IdPerfil
		{
			get
			{
				return this._IdPerfil;
			}
			set
			{
				if ((this._IdPerfil != value))
				{
					this.OnIdPerfilChanging(value);
					this.SendPropertyChanging();
					this._IdPerfil = value;
					this.SendPropertyChanged("IdPerfil");
					this.OnIdPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailUsuario", DbType="VarChar(100)")]
		public string MailUsuario
		{
			get
			{
				return this._MailUsuario;
			}
			set
			{
				if ((this._MailUsuario != value))
				{
					this.OnMailUsuarioChanging(value);
					this.SendPropertyChanging();
					this._MailUsuario = value;
					this.SendPropertyChanged("MailUsuario");
					this.OnMailUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveEncriptada", DbType="VarChar(500)")]
		public string ClaveEncriptada
		{
			get
			{
				return this._ClaveEncriptada;
			}
			set
			{
				if ((this._ClaveEncriptada != value))
				{
					this.OnClaveEncriptadaChanging(value);
					this.SendPropertyChanging();
					this._ClaveEncriptada = value;
					this.SendPropertyChanged("ClaveEncriptada");
					this.OnClaveEncriptadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verificador", DbType="Bit")]
		public System.Nullable<bool> Verificador
		{
			get
			{
				return this._Verificador;
			}
			set
			{
				if ((this._Verificador != value))
				{
					this.OnVerificadorChanging(value);
					this.SendPropertyChanging();
					this._Verificador = value;
					this.SendPropertyChanged("Verificador");
					this.OnVerificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaFirma", DbType="VarChar(MAX)")]
		public string RutaFirma
		{
			get
			{
				return this._RutaFirma;
			}
			set
			{
				if ((this._RutaFirma != value))
				{
					this.OnRutaFirmaChanging(value);
					this.SendPropertyChanging();
					this._RutaFirma = value;
					this.SendPropertyChanged("RutaFirma");
					this.OnRutaFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaFoto", DbType="VarChar(MAX)")]
		public string RutaFoto
		{
			get
			{
				return this._RutaFoto;
			}
			set
			{
				if ((this._RutaFoto != value))
				{
					this.OnRutaFotoChanging(value);
					this.SendPropertyChanging();
					this._RutaFoto = value;
					this.SendPropertyChanged("RutaFoto");
					this.OnRutaFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestriccionBodega", DbType="VarChar(50)")]
		public string RestriccionBodega
		{
			get
			{
				return this._RestriccionBodega;
			}
			set
			{
				if ((this._RestriccionBodega != value))
				{
					this.OnRestriccionBodegaChanging(value);
					this.SendPropertyChanging();
					this._RestriccionBodega = value;
					this.SendPropertyChanged("RestriccionBodega");
					this.OnRestriccionBodegaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPerfilMovile", DbType="Int")]
		public System.Nullable<int> IdPerfilMovile
		{
			get
			{
				return this._IdPerfilMovile;
			}
			set
			{
				if ((this._IdPerfilMovile != value))
				{
					this.OnIdPerfilMovileChanging(value);
					this.SendPropertyChanging();
					this._IdPerfilMovile = value;
					this.SendPropertyChanged("IdPerfilMovile");
					this.OnIdPerfilMovileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoContacto", DbType="Int")]
		public System.Nullable<int> TelefonoContacto
		{
			get
			{
				return this._TelefonoContacto;
			}
			set
			{
				if ((this._TelefonoContacto != value))
				{
					this.OnTelefonoContactoChanging(value);
					this.SendPropertyChanging();
					this._TelefonoContacto = value;
					this.SendPropertyChanged("TelefonoContacto");
					this.OnTelefonoContactoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CVT_SubMenu")]
	public partial class CVT_SubMenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSubMenu;
		
		private int _IdMenu;
		
		private string _Nombre_SubMenu;
		
		private string _URL_SubMenu;
		
		private EntitySet<CVT_PrivilegioPerfil> _CVT_PrivilegioPerfil;
		
		private EntityRef<CVT_Menu> _CVT_Menu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSubMenuChanging(int value);
    partial void OnIdSubMenuChanged();
    partial void OnIdMenuChanging(int value);
    partial void OnIdMenuChanged();
    partial void OnNombre_SubMenuChanging(string value);
    partial void OnNombre_SubMenuChanged();
    partial void OnURL_SubMenuChanging(string value);
    partial void OnURL_SubMenuChanged();
    #endregion
		
		public CVT_SubMenu()
		{
			this._CVT_PrivilegioPerfil = new EntitySet<CVT_PrivilegioPerfil>(new Action<CVT_PrivilegioPerfil>(this.attach_CVT_PrivilegioPerfil), new Action<CVT_PrivilegioPerfil>(this.detach_CVT_PrivilegioPerfil));
			this._CVT_Menu = default(EntityRef<CVT_Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSubMenu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSubMenu
		{
			get
			{
				return this._IdSubMenu;
			}
			set
			{
				if ((this._IdSubMenu != value))
				{
					this.OnIdSubMenuChanging(value);
					this.SendPropertyChanging();
					this._IdSubMenu = value;
					this.SendPropertyChanged("IdSubMenu");
					this.OnIdSubMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMenu", DbType="Int NOT NULL")]
		public int IdMenu
		{
			get
			{
				return this._IdMenu;
			}
			set
			{
				if ((this._IdMenu != value))
				{
					if (this._CVT_Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMenuChanging(value);
					this.SendPropertyChanging();
					this._IdMenu = value;
					this.SendPropertyChanged("IdMenu");
					this.OnIdMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_SubMenu", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Nombre_SubMenu
		{
			get
			{
				return this._Nombre_SubMenu;
			}
			set
			{
				if ((this._Nombre_SubMenu != value))
				{
					this.OnNombre_SubMenuChanging(value);
					this.SendPropertyChanging();
					this._Nombre_SubMenu = value;
					this.SendPropertyChanged("Nombre_SubMenu");
					this.OnNombre_SubMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_SubMenu", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string URL_SubMenu
		{
			get
			{
				return this._URL_SubMenu;
			}
			set
			{
				if ((this._URL_SubMenu != value))
				{
					this.OnURL_SubMenuChanging(value);
					this.SendPropertyChanging();
					this._URL_SubMenu = value;
					this.SendPropertyChanged("URL_SubMenu");
					this.OnURL_SubMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CVT_SubMenu_CVT_PrivilegioPerfil", Storage="_CVT_PrivilegioPerfil", ThisKey="IdSubMenu", OtherKey="IdSubMenu")]
		public EntitySet<CVT_PrivilegioPerfil> CVT_PrivilegioPerfil
		{
			get
			{
				return this._CVT_PrivilegioPerfil;
			}
			set
			{
				this._CVT_PrivilegioPerfil.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CVT_Menu_CVT_SubMenu", Storage="_CVT_Menu", ThisKey="IdMenu", OtherKey="IdMenu", IsForeignKey=true)]
		public CVT_Menu CVT_Menu
		{
			get
			{
				return this._CVT_Menu.Entity;
			}
			set
			{
				CVT_Menu previousValue = this._CVT_Menu.Entity;
				if (((previousValue != value) 
							|| (this._CVT_Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CVT_Menu.Entity = null;
						previousValue.CVT_SubMenu.Remove(this);
					}
					this._CVT_Menu.Entity = value;
					if ((value != null))
					{
						value.CVT_SubMenu.Add(this);
						this._IdMenu = value.IdMenu;
					}
					else
					{
						this._IdMenu = default(int);
					}
					this.SendPropertyChanged("CVT_Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CVT_PrivilegioPerfil(CVT_PrivilegioPerfil entity)
		{
			this.SendPropertyChanging();
			entity.CVT_SubMenu = this;
		}
		
		private void detach_CVT_PrivilegioPerfil(CVT_PrivilegioPerfil entity)
		{
			this.SendPropertyChanging();
			entity.CVT_SubMenu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CVT_Menu")]
	public partial class CVT_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMenu;
		
		private string _Nombre_Menu;
		
		private EntitySet<CVT_SubMenu> _CVT_SubMenu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMenuChanging(int value);
    partial void OnIdMenuChanged();
    partial void OnNombre_MenuChanging(string value);
    partial void OnNombre_MenuChanged();
    #endregion
		
		public CVT_Menu()
		{
			this._CVT_SubMenu = new EntitySet<CVT_SubMenu>(new Action<CVT_SubMenu>(this.attach_CVT_SubMenu), new Action<CVT_SubMenu>(this.detach_CVT_SubMenu));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMenu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMenu
		{
			get
			{
				return this._IdMenu;
			}
			set
			{
				if ((this._IdMenu != value))
				{
					this.OnIdMenuChanging(value);
					this.SendPropertyChanging();
					this._IdMenu = value;
					this.SendPropertyChanged("IdMenu");
					this.OnIdMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Menu", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Nombre_Menu
		{
			get
			{
				return this._Nombre_Menu;
			}
			set
			{
				if ((this._Nombre_Menu != value))
				{
					this.OnNombre_MenuChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Menu = value;
					this.SendPropertyChanged("Nombre_Menu");
					this.OnNombre_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CVT_Menu_CVT_SubMenu", Storage="_CVT_SubMenu", ThisKey="IdMenu", OtherKey="IdMenu")]
		public EntitySet<CVT_SubMenu> CVT_SubMenu
		{
			get
			{
				return this._CVT_SubMenu;
			}
			set
			{
				this._CVT_SubMenu.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CVT_SubMenu(CVT_SubMenu entity)
		{
			this.SendPropertyChanging();
			entity.CVT_Menu = this;
		}
		
		private void detach_CVT_SubMenu(CVT_SubMenu entity)
		{
			this.SendPropertyChanging();
			entity.CVT_Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CVT_PrivilegioPerfil")]
	public partial class CVT_PrivilegioPerfil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPerfil;
		
		private int _IdSubMenu;
		
		private int _Permiso;
		
		private EntityRef<CVT_SubMenu> _CVT_SubMenu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPerfilChanging(int value);
    partial void OnIdPerfilChanged();
    partial void OnIdSubMenuChanging(int value);
    partial void OnIdSubMenuChanged();
    partial void OnPermisoChanging(int value);
    partial void OnPermisoChanged();
    #endregion
		
		public CVT_PrivilegioPerfil()
		{
			this._CVT_SubMenu = default(EntityRef<CVT_SubMenu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPerfil", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPerfil
		{
			get
			{
				return this._IdPerfil;
			}
			set
			{
				if ((this._IdPerfil != value))
				{
					this.OnIdPerfilChanging(value);
					this.SendPropertyChanging();
					this._IdPerfil = value;
					this.SendPropertyChanged("IdPerfil");
					this.OnIdPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSubMenu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdSubMenu
		{
			get
			{
				return this._IdSubMenu;
			}
			set
			{
				if ((this._IdSubMenu != value))
				{
					if (this._CVT_SubMenu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSubMenuChanging(value);
					this.SendPropertyChanging();
					this._IdSubMenu = value;
					this.SendPropertyChanged("IdSubMenu");
					this.OnIdSubMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permiso", DbType="Int NOT NULL")]
		public int Permiso
		{
			get
			{
				return this._Permiso;
			}
			set
			{
				if ((this._Permiso != value))
				{
					this.OnPermisoChanging(value);
					this.SendPropertyChanging();
					this._Permiso = value;
					this.SendPropertyChanged("Permiso");
					this.OnPermisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CVT_SubMenu_CVT_PrivilegioPerfil", Storage="_CVT_SubMenu", ThisKey="IdSubMenu", OtherKey="IdSubMenu", IsForeignKey=true)]
		public CVT_SubMenu CVT_SubMenu
		{
			get
			{
				return this._CVT_SubMenu.Entity;
			}
			set
			{
				CVT_SubMenu previousValue = this._CVT_SubMenu.Entity;
				if (((previousValue != value) 
							|| (this._CVT_SubMenu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CVT_SubMenu.Entity = null;
						previousValue.CVT_PrivilegioPerfil.Remove(this);
					}
					this._CVT_SubMenu.Entity = value;
					if ((value != null))
					{
						value.CVT_PrivilegioPerfil.Add(this);
						this._IdSubMenu = value.IdSubMenu;
					}
					else
					{
						this._IdSubMenu = default(int);
					}
					this.SendPropertyChanged("CVT_SubMenu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
